# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0004_auto_20160801_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group_number',
            field=models.TextField(),
        ),
    ]
