# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginsys', '0006_auto_20160817_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skills_user',
        ),
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
