# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0007_auto_20160819_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skills_number',
            field=models.CharField(choices=[('1', 'Игра на гитаре'), ('2', 'Игра на барабане'), ('3', 'Умение бегать'), ('4', 'Решать ребусы')], default='1', max_length=2),
        ),
    ]
